import { AbsentTeacher } from '../types';

export const MOCK_TEACHERS: AbsentTeacher[] = [
  { id: 't1', name: 'Dr. Smith', department: 'STEM' },
  { id: 't2', name: 'Ms. Jones', department: 'ATCS' },
  { id: 't3', name: 'Mr. Davis', department: 'ABF' },
  { id: 't4', name: 'Mrs. Miller', department: 'AMST' },
  { id: 't5', name: 'Dr. Wilson', department: 'AAST' },
  { id: 't6', name: 'Mr. Taylor', department: 'AVPA' },
  { id: 't7', name: 'Ms. Anderson', department: 'STEM' },
  { id: 't8', name: 'Mr. Thomas', department: 'ATCS' },
  { id: 't9', name: 'Dr. Jackson', department: 'ABF' },
  { id: 't10', name: 'Mrs. White', department: 'AMST' },
  { id: 't11', name: 'Mr. Harris', department: 'AAST' },
  { id: 't12', name: 'Ms. Martin', department: 'AVPA' },
  { id: 't13', name: 'Dr. Thompson', department: 'STEM' },
  { id: 't14', name: 'Mr. Garcia', department: 'ATCS' },
  { id: 't15', name: 'Mrs. Martinez', department: 'ABF' },
  { id: 't16', name: 'Mr. Robinson', department: 'AMST' },
  { id: 't17', name: 'Dr. Clark', department: 'AAST' },
  { id: 't18', name: 'Ms. Rodriguez', department: 'AVPA' },
  { id: 't19', name: 'Mr. Lewis', department: 'STEM' },
  { id: 't20', name: 'Mrs. Lee', department: 'ATCS' },
  { id: 't21', name: 'Dr. Walker', department: 'ABF' },
  { id: 't22', name: 'Mr. Hall', department: 'AMST' },
  { id: 't23', name: 'Ms. Allen', department: 'AAST' },
  { id: 't24', name: 'Dr. Young', department: 'AVPA' },
  { id: 't25', name: 'Mr. Hernandez', department: 'STEM' },
];
