export const theme = {
  colors: {
    background: '#FAF7F2', // Darker (not dark) warm cozy autumn background
    surface: '#FFFFFF',
    surfaceSubtle: '#F6F2EC',
    primary: '#EA580C', // Halloween pumpkin orange
    primarySubtle: '#FFF7ED',
    accentLight: '#FFEDD5',
    absent: '#DC2626',
    absentBg: '#FEF2F2',
    absentText: '#B91C1C',
    present: '#16A34A',
    presentBg: '#F0FDF4',
    textPrimary: '#0F172A',
    textSecondary: '#475569',
    textMuted: '#94A3B8',
    textTertiary: '#94A3B8',
    border: '#E8E2D9',
    borderLight: '#F2ECE3',
    borderStrong: '#CBD5E1',
    divider: '#E8E2D9',
    halloween: {
      orange: '#EA580C',
      orangeLight: '#F97316',
      orangeSubtle: '#FFF7ED',
      warmBg: '#FAF7F2',
      spiderWeb: '#94A3B8',
      bat: '#1E293B',
      pumpkin: '#F97316',
    },
  },
  typography: {
    sizes: {
      screenTitle: 22,
      sectionTitle: 13,
      body: 15,
      bodySmall: 13,
      caption: 11,
      periodNumber: 15,
      tabularNum: 14,
    },
    weights: {
      bold: '700' as const,
      semibold: '600' as const,
      medium: '500' as const,
      regular: '400' as const,
    },
  },
  spacing: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  borderRadius: {
    xs: 3,
    sm: 4,
    md: 6,
    lg: 8,
    full: 9999,
  },
  layout: {
    maxContentWidth: 640,
  },
};
