export const theme = {
  colors: {
    background: '#FFFFFF',
    surface: '#F8FAFC',
    surfaceSubtle: '#F1F5F9',
    primary: '#2563EB',
    primarySubtle: '#EFF6FF',
    accentLight: '#EEF4FE',
    absent: '#DC2626',
    absentBg: '#FEF2F2',
    absentText: '#B91C1C',
    present: '#16A34A',
    presentBg: '#F0FDF4',
    textPrimary: '#0F172A',
    textSecondary: '#475569',
    textMuted: '#94A3B8',
    textTertiary: '#94A3B8',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    borderStrong: '#CBD5E1',
    divider: '#E2E8F0',
  },
  typography: {
    sizes: {
      screenTitle: 22,
      sectionTitle: 13,
      body: 15,
      bodySmall: 13,
      caption: 11,
      periodNumber: 15,
      tabularNum: 14,
    },
    weights: {
      bold: '700' as const,
      semibold: '600' as const,
      medium: '500' as const,
      regular: '400' as const,
    },
  },
  spacing: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  borderRadius: {
    xs: 3,
    sm: 4,
    md: 6,
    lg: 8,
    full: 9999,
  },
  layout: {
    maxContentWidth: 640,
  },
};
